name: CI / CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build Phase: Build the Docker image from the Dockerfile
      - name: Build Docker Image
        run: docker build -t github_reposiory:latest .

      # Test Phase: Run the container and execute tests inside it
      - name: Run Container and Execute Tests
        run: docker run --rm github_reposiory:latest sh -c "/app/run-tests.sh"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Deployment Phase: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "sha._.ima.3" | docker login -u shaimaamaidi --password-stdin

      # Tag the built image for Docker Hub
      - name: Tag Docker Image
        run: docker tag github_reposiory:latest shaimaamaidi/github_reposiory:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push shaimaamaidi/github_reposiory:latest
